[config]
reload_apps = true

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.fuzzel]
input_path = './templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.niri]
input_path = './templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.mako]
input_path = './templates/mako'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.dunst]
input_path = './templates/dunstrc-colors'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'
